### PR TITLE
updated readme with links and screenshots

### LINKED ISSUE #307: Update README with new screenshots
Since the our Site has changed, I think we should update the images (screenshots) in the README.

### PR DESCRIPTION
**Pull request by mani-barathi**
closes #307 

click [here](https://github.com/mani-barathi/Mumble/tree/issue%23307#readme)

### CODE REVIEW

**Comment by MidouWebDev** [comment]
@mani-barathi 
 I think no need to add the vue & django logos in the badges just let them as i have done with MUMBLE LIVE and MUMBLE UI KIT

**Comment by mani-barathi** [comment]
@MidouWebDev removed the links 👍

**Comment by MidouWebDev** [comment]
@mani-barathi i didn't mean to delete the links but just updating them by deleting the vue and django logos
But it is a good idea to mention them here

**Comment by mani-barathi** [comment]
@MidouWebDev If you guys want I'll the badge without logo

 If you guys want I'll the badge without logo

**Comment by mani-barathi** [comment]
@MidouWebDev If you guys want I'll the badges without logo

**Comment by MidouWebDev** [comment]
@mani-barathi yeah do it plz but without the logos

**Pull request merged**
