### PR TITLE
Added Prettier and Eslint configuration files.

### PR DESCRIPTION
**Pull request by i-am-zach**
Before committing, I correctly formatted all the files with prettier so that's why there are so many files changes.

Here is the `.eslint.js` file:
```JavaScript
module.exports = {
  env: {
    browser: true,
    node: true,
    es2021: true,
  },
  extends: [
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
    'plugin:prettier/recommended',
  ],
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 12,
    sourceType: 'module',
  },
  plugins: ['react'],
  settings: {
    react: {
      version: 'detect',
    },
  },
}
```

Here is the `.prettierrc` file:
```JSON
{
  "trailingComma": "all",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "arrowParens": "always",
  "printWidth": 85
}
```

### CODE REVIEW

**Review by codyseibert — APPROVED** [review]

**Comment by Mr-spShuvo** [comment]
It's not recommend to override the default `eslint` (comes with `create-react-app`) over someone's eslint.
What's the point of using `create-react-app`. 
It's not only build tools for creating react app but also the It's the community standards.
Any reason why we need to use your `eslint` config over `create-react-app`?

**Comment by i-am-zach** [comment]
@Mr-spShuvo My main reasoning behind the pull request was to add prettier. In all of the tutorials I saw, they recommended adding the eslint prettier plugin. I was not aware of the default eslint for create-react-app because there was no configuration for it anywhere in the directory. If you'd like, I can close this pull request and send a new one with just the Prettier configuration files.

**Comment by Mr-spShuvo** [comment]
Alright. It's up to @divanov11 
Either he or you can close this or not. Lol. 😂

Yeah, `react-scripts` includes a default battle-proven `prettier` configuration.
We might need not another one.

**Comment by i-am-zach** [comment]
I'll just leave this article here because it gives me the impression adding eslint and prettier to CRA isn't uncommon. https://readwriteexercise.com/posts/setting-up-create-react-app-vs-code-eslint-prettier/

**Comment by codyseibert** [comment]
I'm not too familiar with lint setup, but I'm thinking you'd need to create an .eslint file so that running something like `npx eslint .` will also check that prettier errors don't exist?

**Comment by i-am-zach** [comment]
@Mr-spShuvo If you look at this most recent commit, purged the whole `.eslintrc.js` so that it only extends the default create-react-app linting and the prettier linting. Does this work for you?

**Comment by i-am-zach** [comment]
Closed because of #69

**Pull request closed without merging**
