### PR TITLE
Full responsive and added shadow for cards for better user experience. ( issue #58 )

### PR DESCRIPTION
**Pull request by Rashik4567**
This fork is fully responsive and mobile friendly. And also has improvements in user experience and bug fixed.

### CODE REVIEW

**Comment by MidouWebDev** [comment]
awesome @Rashik4567 !

**Comment by Mr-spShuvo** [comment]
This branch has lot of conflicts. @Rashik4567

**Comment by Rashik4567** [comment]
> This branch has lot of conflicts. @Rashik4567

Its just the formatter.

**Comment by Mr-spShuvo** [comment]
Closing now. Has stylesheet conflicts.
Please. Resolve and re-open for PR.

**Pull request closed without merging**
