### PR TITLE
Correcting mistakes in README.md again because the README.md was updated

### PR DESCRIPTION
**Pull request by MidouWebDev**
I tried to catch mistakes there and here is the pull request again because the README.md was updated without correcting the mistakes

### CODE REVIEW

**Review by Vyvy-vi — COMMENTED** [review]
It looks like there's a conflict in the file.
(This one should be solvable in github itself)
There should be a resolve commits button on there.

**Comment by Vyvy-vi** [comment]
It looks like a space-mismatch
I think you could click on the `Resolve Conflicts` button(it should pop up for you) and remove the stuff in angle brackets
Screenshot 2021-03-31 at 4 10 45 AM

more info-
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Comment by codyseibert** [comment]
@MidouWebDev it looks like there are conflicts again.  Do you think you could just fetch the latest from master and verify the readme still has any mistakes, or close this PR if it seems ok?

**Comment by Mr-spShuvo** [comment]
Closing it favor of new updates.

**Pull request closed without merging**
