### PR TITLE
Created Code of conduct, Contribution guide and license

### PR DESCRIPTION
**Pull request by aathikahamed**
I used Apache-2.0, I'm open to any changes :)

Sorry for not creating 3 different pull requests

### CODE REVIEW

**Comment by vinzvinci** [comment]
There's typo in your issue ~~licence~~ change it to `license`
You can edit your `issue title`

**Comment by aathikahamed** [comment]
I believe `Licence` is British English and `License` in US English. 😄

**Comment by vinzvinci** [comment]
> I believe `Licence` is British English and `License` in US English. 😄

Oh sorry, didn't know about that.

**Review by vinzvinci — APPROVED** [review]
LGTM

**Pull request merged**
