### PR TITLE
add search user/topic and display user card or search topic and topic to intersets (#55)

### PR DESCRIPTION
**Pull request by samuelwondimu**

### CODE REVIEW

**Comment by SamTheFam** [comment]
I had already done this, we'll let Dennis decide, but I think mine has some more functionality.

**Comment by Vyvy-vi** [comment]
Can you maybe link your PR no. @SamTheFam ?
(This would help Dennis in knowing that both the PRs are doing similar things)

You can link your pr using a # -> #<pr no.>

**Comment by samuelwondimu** [comment]
.

**Comment by codyseibert** [comment]
attaching screenshots so we know what this functionality looks like added in: 

Screen Shot 2021-04-01 at 6 13 00 PM

Screen Shot 2021-04-01 at 6 13 49 PM

**Comment by codyseibert** [comment]
@samuelwondimu would you be able to resolve the conflicts and we can merge?  Thank you!

**Comment by divanov11** [comment]
I have a template and design to implement this already so we can close out this PR.

**Pull request closed without merging**
