### PR TITLE
[repo] GitHub issue templates 

### PR DESCRIPTION
**Pull request by abhivemp**
As discussed in issue #22 - issue templates allow having some consistency and provides a framework for people in the open-source community. 

I have drafted a bug template and a new feature template. Looking forward to everyone's feedback. 

@divanov11 @Mr-spShuvo

### CODE REVIEW

**Comment by codyseibert** [comment]
What is the .github/Untitled.md file added for?  Otherwise, it looks like a good start to me to help get consistency.

**Comment by abhivemp** [comment]
@codyseibert good catch! I am not sure either 🤣 
I'll remove it right now. 
Do you think there are other templates we can add? Or do you think we should add more questions in the template?

**Review by codyseibert — APPROVED** [review]

**Comment by abhivemp** [comment]
@codyseibert I didn't delete the untitled.md... should I commit again?

**Comment by Vyvy-vi** [comment]
welp it's merged now

**Comment by Vyvy-vi** [comment]
Whoever edits the `.github` folder next, could maybe remove that file or someone with write access to the repo can delete it

**Comment by Vyvy-vi** [comment]
There's also another issue, the folder should be called `ISSUE_TEMPLATE` instead of `ISSUE_TEMPLATES`

**Pull request merged**
