### PR TITLE
🔥 Sidebar Navigations

### PR DESCRIPTION
**Pull request by Mr-spShuvo**
#### A sidebar navigation has been added to mumble projects.

**Desktop**

image

**Mobile**
image

### CODE REVIEW

**Comment by MidouWebDev** [comment]
@Mr-spShuvo There is a bug in the login page

bug-login-page-shuvo-pr

**Comment by codyseibert** [comment]
Yaaaaass this is nice!

**Review by codyseibert — APPROVED** [review]

**Comment by Mr-spShuvo** [comment]
@MidouWebDev It's not a issue with this PR.
May be create an Another issue mentioning with the Display Resolution.

**Comment by Mr-spShuvo** [comment]
> Yaaaaass this is nice! Good merge unless you want another reviewer

@divanov11  wants to have a look before I'm merging this. 
Let's just wait for his approval.

**Comment by MidouWebDev** [comment]
@Mr-spShuvo
If you check the mumble website now, you will notice that we don't have the problem i mentionned !

**Comment by Mr-spShuvo** [comment]
Alright I checked. No Issues on my end. Also, 
I did not touch any styles on `LoginSignup.css`.
May be it on your device only things.
Can you share your device resolution and browser info?
@MidouWebDev

**Comment by MidouWebDev** [comment]
> Alright I checked. No Issues on my end. Also,
> I did not touch any styles on `LoginSignup.css`.
> May be it on your device only things.
> Can you share your device resolution and browser info?
> @MidouWebDev

@Mr-spShuvo i am on Google Chrome, Laptop 15.6" Display

**Pull request merged**
