### PR TITLE
Added dark mode

### PR DESCRIPTION
**Pull request by EugeneGohh**
Prior to this issue (**dark mode & light mode features #21**), I have worked on dark mode and added functionality & dark mode icon. Feel free to make some changes to it.

Prior to this issue (**Word Enhancement #60**), I have replaced **change** to **navigate**.

### CODE REVIEW

**Comment by EugeneGohh** [comment]
> This is cool, I checked it out and played around with it! Although, I'm not sure how others might feel about StyledComponents for dark mode instead of just using CSS variables to toggle the colors. So far I think they are learning towards using BEM for components, so StyledComponents might go against that approach? Just a thought!

Sorry if I made it wrong, I'm not really sure what they're using but I saw an issue about **dark mode & light mode features** and I decided to contribute to it. Also, I don't have any knowledge of BEM for components.

**Comment by abhivemp** [comment]
Not bad! Excellent stuff @EugeneGohh 
Do you think it's possible if you can add screenshots so anyone who doesn't have the project on their computer can see?

**Comment by EugeneGohh** [comment]
**Light mode ->**

localhost_3000_

**Dark mode ->**

localhost_3000_ (1)

**Comment by Mr-spShuvo** [comment]
We are planning to not using Styled Components. Also, we're planning to go full dark mode not just background. I'm closing this, but you can also do an improvement and reopen this.

**Pull request closed without merging**
