### PR TITLE
cleaned up App.js & added user state to ease up the dev process

### PR DESCRIPTION
**Pull request by mani-barathi**

### CODE REVIEW

**Comment by codyseibert** [comment]
I don't think this is the functionality Dennis is looking for.  This functionality change in the PR prevents any of the other routes from being accessed unless you are logged in.  They want this application to still be viewable even without being logged in.

**Comment by mani-barathi** [comment]
Are you sure ? that means anybody can access any route?

**Comment by Vyvy-vi** [comment]
I think that's what the application is supposed to have

**Comment by mani-barathi** [comment]
@Vyvy-vi  Do you mean what I proposed is correct?

**Comment by Vyvy-vi** [comment]
> @Vyvy-vi Do you mean what I proposed is correct?
They want this application to still be viewable even without being logged in.

**Comment by mani-barathi** [comment]
> > @Vyvy-vi Do you mean what I proposed is correct?
> 
> They want this application to still be viewable even without being logged in.

ok fine Got it

**Comment by i-am-zach** [comment]
@mani-barathi I think you were actually just a little too early on this. We are probably going to want to want functionality like this once we have a connected backend. Right now, the site is meant to be a static showcase of the components (someone correct me if I'm wrong). I'd save this code until then and resubmit a PR.

**Comment by mani-barathi** [comment]
@i-am-zach Let's see if this is required I'll resubmit a PR

**Pull request closed without merging**
