### PR TITLE
Added Create Discussion Route

### LINKED ISSUE #125: Create Discussion Component / Route
There currently is no page for creating a new discussion.  We have a link called "Start a Discussion", but it doesn't navigate the user to any usable page.  This feature would include the following work:

- create a new page/route for people to create a discussion
- a user shall be able to type into a text area and click on a submit button
- after clicking the submit button, it should redirect them to a discussion/:slug page
- clicking on the "Start a Discussion" button should navigate the user to this create discussion page

### Notes
Since we don't have an API, there is no need to implement any real logic other than maybe using a useState hook to keep track of what the user typed.

This button should do something:
Screen Shot 2021-04-03 at 8 39 39 PM

### PR DESCRIPTION
**Pull request by mani-barathi**
closes #125 

image

### CODE REVIEW

**Comment by Mr-spShuvo** [comment]
Not sure how we are gonna layout that page. Let' see what @divanov11  thinks.

**Comment by codyseibert** [comment]
LGTM.  It seems like a good start even if it isn't 100% what @divanov11 has in mind in the future.

**Comment by divanov11** [comment]
Looks good to me! I’ll get on my computer to resolve the conflicts in a bit.

**Comment by mani-barathi** [comment]
@codyseibert @divanov11 👍

**Pull request merged**
